server:
     port: 8080

spring:
     application:
          name: SpringBoot
          
logging:
     level:
         root: INFO
     file:     
         name: C://Tools//springboot//logs/springboot-exceptionhandling.log 