INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE ) 
VALUES(10001,  'Gaurav', 'Noida', CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE ) 
VALUES(10002,  'Amit', 'Delhi',CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE ) 
VALUES(10003,  'Punit', 'Mumbai',CURRENT_TIMESTAMP());
