INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('SCALA BY XYZ', 'XYZ', 50.0);
INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('JAVA BY SBA', 'SBA',20.0);
INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('ANGULAR BY TRT', 'TRT',70.0);
INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('NODE BY IYT', 'IYT',30.0);