INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE ) 
VALUES(10001,  'Gaurav', 'Noida', CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE ) 
VALUES(10002,  'Amit', 'Delhi',CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTHDATE ) 
VALUES(10003,  'Punit', 'Mumbai',CURRENT_TIMESTAMP());

INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('SCALA BY XYZ', 'XYZ', 50.0);
INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('JAVA BY SBA', 'SBA',20.0);
INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('ANGULAR BY TRT', 'TRT',70.0);
INSERT INTO BOOK (NAME, AUTHOR, PRICE ) VALUES('NODE BY IYT', 'IYT',30.0);
