/*
INSERT INTO TUTORIAL (TITLE, DESCRIPTION, PUBLISHED, PERSONID ) 
VALUES('JAVA', 'JAVA by ABD', 1);
INSERT INTO TUTORIALS (TITLE, DESCRIPTION, PUBLISHED ) 
VALUES('SPRING', 'SPRING by HGJ',0);
INSERT INTO TUTORIALS (TITLE, DESCRIPTION, PUBLISHED ) 
VALUES('ANGULAR', 'ANGULAR by WERV',1);
INSERT INTO TUTORIALS (TITLE, DESCRIPTION, PUBLISHED ) 
VALUES('NODE', 'NODE by FGFD',1);
INSERT INTO TUTORIALS (TITLE, DESCRIPTION, PUBLISHED ) 
VALUES('SCALA', 'SCALA by YURT',1);


*/ 	